[package]
name = "lnpbp"
version = "0.1.0-alpha.2"
license = "MIT"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "LNP/BP Core Library implementing LNPBP specifications & standards"
repository = "https://github.com/LNP-BP/rust-lnpbp"
homepage = "https://github.com/LNP-BP"
keywords = ["bitcoin", "lightning", "lnp-bp", "layer-3", "cryptography"]
readme = "README.md"
edition = "2018"

[lib]
name = "lnpbp"
path = "src/lib.rs"

# Dependencies version policy
# ---------------------------
# The policy in specifying dependencies versions are to use tilde requirements
# according to https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html?highlight=feature#tilde-requirements
# with full semver version specification (major, minor and patch components)
# which means that we may upgrade for patches/bugfixes, but must not change
# even the minor version of the package.
# Once the library is stable consider upgrading tilde requirements to strict
# equivalence requirements (with '=' sign) since even dependencies patching will
# not introduce risk of breaking the consensus and even security updates must
# be done manualy after through testing
[dependencies]
bitcoin = { git = "https://github.com/LNP-BP/rust-bitcoin", branch = "staging" }
lightning = { git = "https://github.com/LNP-BP/rust-lightning", branch = "staging", optional = true }
lightning-net-tokio = { git = "https://github.com/LNP-BP/rust-lightning", branch = "staging", optional = true }
miniscript = { git = "https://github.com/LNP-BP/rust-miniscript", branch = "staging" }
grin_secp256k1zkp = { git = "https://github.com/LNP-BP/rust-secp256k1-zkp", branch = "stable", optional = true }
rand = "~0.7.3" # Required by grin_secp256k1zkp
derive_wrapper = "~0.1.6"
#derive_wrapper = { git = "https://github.com/LNP-BP/derive-wrapper", branch = "stable" }
num-traits = "~0.2.11"
num-derive = "~0.3.0"
tokio = { version = "~0.2.18", features = ["tcp"], optional = true }
futures = "~0.3.4"
torut = "~0.1.2"
async-trait = { version = "~0.1.30", optional = true }
log = { version = "~0.4.8", features = ["max_level_trace", "release_max_level_debug"], optional = true }
zmq = { version = "~0.9.2", optional = true }
parse_arg = { version = "~0.1.4", optional = true }
petgraph = { version = "~0.5.0", optional = true }
# This strange naming is a workaround for not being able to define required features for a dependency
# See https://github.com/rust-lang/api-guidelines/issues/180 for the explanation and references.
serde_crate = { package = "serde", version = "~1.0.106", features = ["derive"], optional = true }

[dev-dependencies]
miniscript = { git = "https://github.com/LNP-BP/rust-miniscript", branch = "staging", features = ["compiler"] }

[features]
default = []
all = ["tor", "lightning", "tokio", "log",
       "bulletproofs", "rgb", "daemons", "parse_arg", "serde"]
async = ["async-trait"]
rgb = ["bulletproofs", "petgraph"]
tor = ["torut/v3", "torut/v2"]
lightning_tokio = ["lightning", "lightning-net-tokio"]
bulletproofs = ["grin_secp256k1zkp"]
api = ["zmq"]
daemons = ["async", "api"]
serde = ["serde_crate", "torut/serialize", "bitcoin/use-serde", "miniscript/serde"]
